=== mormulms/SitOPT/situation_template_mapping/situation_template_draft01.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- XML Schema definition of a SituationTemplate to observe sensor data and detects occurring situations -->
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<!-- root -->
	<xs:element name="SituationTemplate" type="tSituationTemplate"/>
	
	<xs:complexType name="tSituationTemplate">
		<xs:sequence>
			<xs:element name="situationNode" type="tSituationNode" maxOccurs="unbounded"/>
			<xs:element name="operationNode" type="tOperationNode" maxOccurs="unbounded"/>
			<xs:element name="conditionNode" type="tConditionNode" maxOccurs="unbounded"/>
			<xs:element name="contextNode" type="tContextNode" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tSituationNode">
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tOperationNode">
		<xs:sequence>
			<xs:element name="parent" type="tParent" minOccurs="0" maxOccurs="unbounded"/>
			<xs:element name="type">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="and"/>
						<xs:enumeration value="xor"/>
						<xs:enumeration value="or"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="negated" type="xs:boolean" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="tTimeNode">
		<xs:complexContent>
			<xs:extension base="tConditionNode">
				<xs:sequence>
			                <xs:element name="amountIntervals" type="xs:positiveInteger" minOccurs="1" maxOccurs="1"/>
			        </xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
		
	<!-- TODO (?): set use="required" on parent element of sensor nodes, each sensor should be processed -->
	<xs:complexType name="tContextNode">
		<xs:sequence>
			<xs:element name="parent" type="tParent" minOccurs="1" maxOccurs="unbounded"/>
			<xs:element name="inputType" minOccurs="1" maxOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="sensor" />
						<xs:enumeration value="situation" />
						<xs:enumeration value="static" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="measureName" type="xs:string" minOccurs="0" maxOccurs="1" />
			<xs:element name="unit" type="xs:string" minOccurs="0" maxOccurs="1" />
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
		<xs:attribute name="type" type="xs:string" use="required"/>
	</xs:complexType>
	
	<!-- main processing node. TODO: handle sub-situations -->
	<xs:complexType name="tConditionNode">
		<xs:sequence>
			<xs:element name="opType" maxOccurs="1" minOccurs="1">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="lowerThan"/>
						<xs:enumeration value="greaterThan"/>
						<xs:enumeration value="equals"/>
						<xs:enumeration value="notEquals"/>
						<xs:enumeration value="between"/>
						<xs:enumeration value="average"/>
						<xs:enumeration value="min"/>
						<xs:enumeration value="max"/>
						<xs:enumeration value="intervalMinEqual"/>
						<xs:enumeration value="intervalMin"/>
						<xs:enumeration value="intervalMaxEqual"/>
						<xs:enumeration value="intervalMax"/>
						<xs:enumeration value="sensorLowerThan" />
						<xs:enumeration value="sensorGreaterThan" />
						<xs:enumeration value="sensorEquals" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="condValues">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="value" type="xs:string" maxOccurs="2"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="parent" type="tParent" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="id" type="xs:ID" use="required"/>
		<xs:attribute name="name" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="tParent">
		<xs:attribute name="parentID" type="xs:IDREF"/>
	</xs:complexType>

</xs:schema>

=== mormulms/SitOPT/situation_template_mapping/test/situation_template_draft01.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
			<parent parentID="A10"/>
			<negated>false</negated>
		</operationNode>
		<conditionNode id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValues>
				<value>70</value>
			</condValues>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A8" name="MB RAM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValues>
				<value>10</value>
			</condValues>
			<parent parentID="A3"/>
		</conditionNode>
		<contextNode id="A5" type="memorySensor">
			<parent parentID="A8"></parent>
            <inputType>sensor</inputType>
		</contextNode>
		<contextNode id="A6" type="cpuSensor">
			<parent parentID="A4"></parent>
            <inputType>sensor</inputType>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/moreLevelTree.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A15" name="hyper combine">
			<type>xor</type>
			<parent parentID="A10"/>
			<negated>true</negated>
		</operationNode>

		<operationNode id="A11" name="super combine">
			<type>xor</type>
			<parent parentID="A15"/>
			<negated>false</negated>
		</operationNode>

		<operationNode id="A12" name="combine Sensors2">
			<type>or</type>
			<parent parentID="A11"/>
			<negated>true</negated>
		</operationNode>
		<conditionNode id="A13" name="MyCondNode">
			<type>type</type>
			<opType>lowerThan</opType>
			<condValue>
				<value>30</value>
			</condValue>
			<parent parentID="A12"/>
		</conditionNode>
		<contextNode id="A14" name="MyContextNode">
			<parent parentID="A13"/>
		</contextNode>
		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
			<parent parentID="A11"/>
			<negated>true</negated>
		</operationNode>
		<conditionNode id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A8" name="MB RAM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValue>
				<value>10</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A9" name="StatusCodeChecker">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>notEquals</opType>
			<condValue>
				<value>200</value>
			</condValue>
			<parent parentID="A3"></parent>
		</conditionNode>
		<contextNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</contextNode>
		<contextNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
		</contextNode>
		<contextNode id="A7" name ="watchdogSensor">
			<parent parentID="A9"/>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/demoTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
			<parent parentID="A10"/>
			<negated>false</negated>
		</operationNode>
		<conditionNode id="A9" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValues>
				<value>0</value>
			</condValues>
			<parent parentID="A3"/>
		</conditionNode>
		<contextNode id="A7" type="watchdogSensor">
			<parent parentID="A9"/>
			<inputType>sensor</inputType>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/situation_template_draft02.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A2" name="AND (CPU and RAM sensor)">
			<parent parentID="A3"/>
			<type>and</type>
		</operationNode>
		<operationNode id="A3" name="OR (rootNode)">
			<type>or</type>
			<parent parentID="A9"/>
		</operationNode>
		<conditionNode id="A4" name="CPU high load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="A2"/>
		</conditionNode>
		<conditionNode id="A8" name="RAM full">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>90</value>
			</condValue>
			<parent parentID="A2"/>
		</conditionNode>
		<contextNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</contextNode>
		<contextNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
		</contextNode>
		<contextNode id="A7" name ="watchdogSensor">
			<parent parentID="A3"/>
		</contextNode>
		<situationNode name="machine_failed" id="A9"/>	
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/multipleSituations.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="B3" name="combine Sensors">
			<type>and</type>
			<parent parentID="B10"/>
			<negated>true</negated>
		</operationNode>
		<conditionNode id="B4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="B3"/>
		</conditionNode>
		<conditionNode id="B8" name="MB RBM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValue>
				<value>10</value>
			</condValue>
			<parent parentID="B3"/>
		</conditionNode>
		<conditionNode id="B9" name="StatusCodeChecker">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>notEquals</opType>
			<condValue>
				<value>200</value>
			</condValue>
			<parent parentID="B3"></parent>
		</conditionNode>
		<contextNode id="B5" name="memorySensor">
			<parent parentID="B8"></parent>
		</contextNode>
		<contextNode id="B7" name ="watchdogSensor">
			<parent parentID="B9"/>
		</contextNode>
		<situationNode name="machine_failed" id="B10"/>

		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
			<parent parentID="A10"/>
			<negated>true</negated>
		</operationNode>
		<conditionNode id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A8" name="MB RAM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValue>
				<value>10</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A9" name="StatusCodeChecker">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>notEquals</opType>
			<condValue>
				<value>200</value>
			</condValue>
			<parent parentID="A3"></parent>
		</conditionNode>
		<contextNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</contextNode>
		<contextNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
			<parent parentID="B4"></parent>
		</contextNode>
		<contextNode id="A7" name ="watchdogSensor">
			<parent parentID="A9"/>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/handlerTest.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
	<Situation id="A1" name="SystemFailure">
		<operationNode id="A6" name="AND">
			<parent parentID="A10" />
			<type>and</type>
			<negated>false</negated>
		</operationNode>
		<conditionNode id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValue>
				<value>10</value>
			</condValue>
			<parent parentID="A6"/>
		</conditionNode>
		<contextNode id="A5" type="distance">
			<parent parentID="A4"/>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
	</Situation>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/compareSensors.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
		        <parent parentID="A10"/>
		        <negated>true</negated>
		</operationNode>
		<conditionNode id="A4" name="multipleSensors">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>sensorLowerThan</opType>
			<condValue>
			</condValue>
			<parent parentID="A3" />
		</conditionNode>
		<contextNode id="A5" name="memTest">
			<parent parentID="A4"></parent>
		</contextNode>
		<contextNode id="A6" name="cpuSensor">
			<parent parentID="A4"></parent>
		</contextNode>
		<contextNode id="A7" name ="watchdogSensor">
			<parent parentID="A4"></parent>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>

=== mormulms/SitOPT/situation_template_mapping/test/averageCheck.xml
<?xml version="1.0" encoding="UTF-8"?>
<SituationTemplate id="A0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="situation_template_draft01.xsd"
	name="SystemObservation">
		<operationNode id="A3" name="combine Sensors">
			<type>and</type>
			<parent parentID="A10"/>
			<negated>true</negated>
		</operationNode>
		<conditionNode id="A4" name="% CPU load">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>greaterThan</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A11" name="average" xsi:type="tTimeNode">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>average</opType>
			<condValue>
				<value>70</value>
			</condValue>
			<parent parentID="A3"/>
			<amountIntervals>3</amountIntervals>
		</conditionNode>
		<conditionNode id="A8" name="MB RAM free">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>lowerThan</opType>
			<condValue>
				<value>10</value>
			</condValue>
			<parent parentID="A3"/>
		</conditionNode>
		<conditionNode id="A9" name="StatusCodeChecker">
			<type>type</type>
			<measureName>measureName</measureName>
			<opType>notEquals</opType>
			<condValue>
				<value>200</value>
			</condValue>
			<parent parentID="A3"></parent>
		</conditionNode>
		<contextNode id="A5" name="memorySensor">
			<parent parentID="A8"></parent>
		</contextNode>
		<contextNode id="A6" name="cpuSensor">
			<parent parentID="A11"></parent>
		</contextNode>
		<contextNode id="A7" name ="watchdogSensor">
			<parent parentID="A9"/>
		</contextNode>
		<situationNode name="machine_failed" id="A10"/>
</SituationTemplate>
